[programs.localnet]
vestly = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkgSNpHjG7xkX"

[programs.devnet]
vestly = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkgSNpHjG7xkX"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[profile.release]
overflow-checks = true
