[programs.localnet]
vestly = "GWGc6ZSvpwQ6VTUE7KHRi2pfddh9Ua16PQYE9yj9aS14"

[programs.devnet]
vestly = "GWGc6ZSvpwQ6VTUE7KHRi2pfddh9Ua16PQYE9yj9aS14"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[profile.release]
overflow-checks = true
